### ISSUE TITLE
HCRの図で100％を超える部分について

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr23#112]
HCRの図（https://github.com/ichimomo/frasyr23/blob/master/tools/aka2.pngの真ん中の図）ですが，資源量水準（％）とあるｘ軸，理論的には100％を超えることがないのに，この図では100％を超える範囲まで描画されています．ここのところ，100％が最大になるように修正していただけないでしょうか？

**Comment by fshin3** [comment]
dev ブランチはREADMEも書き換わっているんですが、masterにはまだ反映されていないのです（大きなバグ見つけてしまったんで処理してました）。
