### ISSUE TITLE
BLが同じ時のplot_hcr2でのエラー

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr23#175]
以下のようなエラーが出ました
`Error in intersection_hcrs(res.list.inters) : object 'Delta2.1' not found`

調べてみますと以下のコードの箇所かと思います。
https://github.com/ichimomo/frasyr23/blob/cb6cb2d8370e57b6f758e8acd01458b9b32a94f0/R/abc_23.r#L1400-L1407

両HCRのBLが同じ場合、このif文に引っかからないことが分かりました。

@fshin3 さん、お手すきの際、ご確認お願いします。

**Comment by fshin3** [comment]
直したので動作確認してみてください
